#
# For continuous deployment, keys are encrypted using Travis file encryption functionality:
# https://docs.travis-ci.com/user/encrypting-files
#

language: java
jdk: oraclejdk8

branches:
  only:
    - /^hotfix.*$/
    - /^feature.*$/
    - develop

git:
  depth: false

env:
  global:
    - secure: RO3fvGp6orwCoPtV5v/lUwxbFomsSxdficUHFbYGEXB+NuxpjES5Ukd9D/4zn1WytL/h1mlgcML+gSR57OKODX9SJXyMYMSRQslbOSYVle4sxGf5sp54bkGaaHI6aZr2ZbjzBwVYemR+zFpWQMew2Q4cZ4pn5HfQQa7WlJ/qNnOZ2KXqgEaIuw++aQg0QEaddleMTzMDZpFUdESIY/ptAjve2BAbsHw07AI9tX08qYFJ+fzZWKmKY2EBHd4HztZcU1lQwMuxxTzDmjFKksrjSH37wmHg/D2t7ptlQIaKJuTgD9HFqMd7Gf7DFeNdadoHLxWuqa7Yt9y2plMykRctYLCBr5z6ofq+RWFlXFS/bEwzHGxDkT9PLbhWewPF/JsmERj4x/DYLRQYPq2d/3VOCrpoLKagmLzOGusbaLr15ISel0bDXhNyXg1jdQXY7EZUksbM90Ny+CuAHP4nsW0PUgNLBVb1CjGhi4OGW4ohXj0a2cG/lGMeeZXGUEwwd6xKXcWwGBKm/mqZJsIQDJX+he1P23hrtaV/mbhh1U4zjKqVwRzBXYhjAQwnulVS7JC5dFeYifXEjib30Vz3QCnssMg7hzYSBu1IvvukHjkMoPaULWiGIvgdVN+Hy7syrqe48GGdYLbgbzLhn6I6aklPh6Y9z9vPhFtQiHMf1k6tA30=
    - secure: 36z73CBVF2FZzndNUxhfc8T2ty3ebX4sWLYyR5DdCyDfOGjgZlJtcX8DZ9StRvnZptgs/mcma93ihQ4OCWLyTEjBom+PYoeHkE2/gUwCzYA4g5xnw0eEUd1+ZKiNPmrfHu41wsPjPSgqiptlhqTvzpenJlXVqmt/jGEiXvfruwPWYX3ZGpzroczaWh24WCDyoGb19O5HN4GxBt5keR7aI9j0AJdEc7GHKDD9v0y0yXzSOSZ/vNGHJuDiPSf5sg8FcjvV+LVsP8Ge31CpK51AKbJqDo4gmgaEAi1p+cRAYba9bUUIY6GXpH25hImLtNqKmSZLRyOdH9hA8vM7c1+Zgk3CSyeWuh9fhUtNQt0JKj6iJ7ZqhFzVId2qn4fe+aEIYo2KLUxSKfs9Jcfh89QRDDdWPL8oWVg7+bos692zIOR+bgOnikHqNbOuWFiRINdBgs+DIvUsF6qZNQJftd+8D+TlRDJ1HBjLsy71TIAgOyhrc1SKTlB7CLiWZitrWkJy+IoeLqd6wRp1h6uOvS0syiQAoadnzcyuWG4xA1pdGypNcR8ebfycTa0bBi0FppZt0e5uxI5lBsONrGEujTEtFJ0rT92rfjxZpZQ+ruN0OI48z2QBE5UmyVCNSnQVnUPI7/JYGcJ/RDiqoaZqZU3XR8WnJ70PZsb8P0xpNyASFLw=
    - secure: QueSN/tSIcihbF8JIWHu1piFpuzSQggtnMFwSqZ3Yjzip1SyAUNe5HaP2BU+3EaWQBG8jgxsFQqRl/ldsrUUTXc29OtgQRiI+Ybo0O/5IdmnmTpeWjiBRdBYEY1t4ROyvVRP7Fs2VRFNL2L8fJdjOsjUyxdBItuGaW7bPeU6Gd3SlTPZ3F/uNSNv+zC9ek/JziYWlVryUV5so8ymhuzMfTBoj7qnlOKn9Xo4JNJlfIVPsZAFtYQNkgEAqhztpikILfyWXYYI1NM0gMo5qycksnFmZCvNWIQBT5wKuLfZGyQB5529mT/wAbVnUyjX3+y6bBr7COKkjeyYz1UYc/dYX6afP1ss19Pm9iKKTwo+S4qx7FjTaF1eov0W3Y5+o8Xk5TQa5cOe3Y6nWTXypm93UgMU0EyXbnJ9cF44dlQ0Ls+DjHb0TToiPLxyRwm67zPEC+XQ4ne5lm7Xbkx5AYpaH90Y0PPCLdwlL9AzMehFGox/L2U8RAcDz2e/v0Ekmy1/Vqtg8FUcF1k1Jl+7k7ipu6xMO1mFVUxBHc4XPww7tMMxfwOcjh2go5jTLYwENA6GbYnkPW/ktQRmf7VarnSFkZnVLZ9AJ7tR0qZos5zomaQLi4eZhtfEKO5Cq3H7x8lCnca7Sf2nCqvLz9yxbTGga4JLEzeupw+rhj4HI+jOxyk=
    - secure: QbVp2q32kFmy6bUiXDA1IcFREsV15j/VepWnnv29+Jz4I/Kwsfc5d/CSHkwQ+kArokRTKdOyYAm5FdCgDHeRwQwAuy+n/hydDfjORxMOjzcEf9JSoqsc+EqLOi9y0tqUIMEuSOY/MHX+zV10O/GmvuLxEArc8zzrUn240jRHOUwtgfKyTN8TuoS3wzd/h4l8UY2bh+KrqROwEV5nztWEUvCJ1UcCzg1c9ItDJhXLLTrHhWw7tz5dCHyvot2jOYiUCB8/QRd77Nu6n8cMrFe9Nm0v98cOaDExMqgOM1/XAzrjHK/mlqmU1HjPNRCZ5jZ3mgy99mTAuSpVMwPLoeogOYDPnaUMSInBPVeU+cWVvsp/AlpttzDwLbRLAiPoqBmTBN1OoFCT1LgXt8dQ+9uR6V5qnnUv5WRDikPRQ/nwnXGyIz10pFbISaJmO74h5Nk74Ec4swX+x3mMekN0bZDXdLykCk4mQsDnDMojYxCYb6+OG0chQ7BcXP9TH44YrLrgYDe67dYPHga1+n1kCfuIGx8jp99uuKnMOUazaHa6Du9WyuPt1VaJSTd+Eh/Q1VJHsBoCpveCJPmGDYcw8slKsOIBI1dv1Yu9pgcF2tRd36nzUVyQ5bL51roWD55ul0Kv068jW5d1uiX2dNdYxjAyVM5zhoOV3G+X4yb7ldY8Ok8=

before_cache:
  - find $HOME/.gradle/caches -type f -name '*.lock' -delete
  - find $HOME/.gradle/caches -type f -name 'file-access.bin' -delete
  - find $HOME/.gradle/caches -type d -name 'workerMain' -delete
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $HOME/.gradle/caches/*/scripts*/
  - rm -rf $HOME/.gradle/caches/*/fileHashes/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/native/
    - $HOME/.gradle/wrapper/

services:
  - mongodb
  - rabbitmq
  - postgresql

install:
  # Git set up is required for release tag creation
#  - git remote set-url origin https://$GRGIT_USER:$GRGIT_PASS@github.com/hexagonkt/hexagon.git
  - git pull origin develop
  - git pull origin master
  - mongo hexagon_benchmark/mongodb.js
  - psql -U postgres -f hexagon_benchmark/postgresql.sql

script: ./gradlew --quiet --stacktrace clean all

after_success: bash <(curl -s https://codecov.io/bash)
after_failure: echo 'Look for FAILURE in tests'

deploy:

  - provider: script
    script: ./gradlew --no-daemon --stacktrace --debug debug
    on:
      branch: develop

  - provider: script
    script: ./gradlew --no-daemon --quiet --stacktrace clean all release
    on:
      branch: master

  - provider: pages
    skip_cleanup: true
    github_token: $GRGIT_PASS
    local_dir: hexagon_site/build
    fqdn: hexagonkt.com
    on:
      branch: master
